
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 25 23:44:45 CST 2015
//----------------------------------------------------

package ASintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BRA_IZQ = 12;
  public static final int PAR_DER = 9;
  public static final int OPREL_MAI = 31;
  public static final int SELECT_CASE = 20;
  public static final int END_FOR = 43;
  public static final int OPSUM = 14;
  public static final int END_CASE_OPT = 25;
  public static final int CHAR = 53;
  public static final int BEGIN_WHILE = 39;
  public static final int IF_THEN = 45;
  public static final int END_MAIN = 3;
  public static final int CHAR_ARRAY = 52;
  public static final int DOUBLE = 58;
  public static final int CASE_OPT = 23;
  public static final int FOR = 41;
  public static final int WRITE = 48;
  public static final int BEGIN_FOR = 42;
  public static final int NOT = 13;
  public static final int AND = 18;
  public static final int IGUAL = 60;
  public static final int OPRES = 15;
  public static final int DOUBLE_NUM = 55;
  public static final int DEFAULT_CASE = 26;
  public static final int OR = 19;
  public static final int WRITE_LN = 49;
  public static final int NUM = 51;
  public static final int ELSE_IF = 47;
  public static final int IF = 44;
  public static final int BRA_DER = 11;
  public static final int MAIN = 2;
  public static final int ID = 62;
  public static final int END_WHILE = 40;
  public static final int CHAR_OPER = 36;
  public static final int EOF = 0;
  public static final int RETURN = 59;
  public static final int ASIG = 54;
  public static final int BOOL_OPER = 35;
  public static final int BEGIN_CASE_OPT = 24;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int COMA = 8;
  public static final int BEGIN_PROCEDURE = 5;
  public static final int END_DEFAULT_CASE = 27;
  public static final int END_IF = 46;
  public static final int PAR_IZQ = 10;
  public static final int VOID = 61;
  public static final int OPDIV = 17;
  public static final int PCOMA = 7;
  public static final int OPREL_MEQ = 28;
  public static final int OPREL_MEI = 30;
  public static final int READ = 50;
  public static final int WHILE = 38;
  public static final int END_PROCEDURE = 6;
  public static final int OPREL_DIST = 32;
  public static final int STRING = 57;
  public static final int INT_NUM = 37;
  public static final int BEGIN_SELECT_CASE = 21;
  public static final int FALSE = 34;
  public static final int OPREL_MAQ = 29;
  public static final int OPMULT = 16;
  public static final int PROCEDURE = 4;
  public static final int END_SELECT_CASE = 22;
  public static final int INCREMENTADORES = 56;
}

